name: japfa_internship
description: "Proyek Tugas Akhir"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  flutter_pdfview: ^1.0.0
  flutter_webview_plugin: ^0.4.0
  flutter_riverpod: ^2.0.0
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  dio: ^5.0.0
  freezed_annotation: ^3.0.0
  json_annotation:  ^4.9.0
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets: 
    - assets/japfa_buduran_landscape.jpg
    - assets/department_card/
    - assets/timeline/
    - assets/file_upload_peserta/
    - assets/file_upload_peserta/dummy_foto_diri.png
    - assets/japfa_logo_only.png
    - assets/japfa_logo_background.png

    - assets/default_profile.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
